import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div
          style={{
            backgroundColor: "beige",
            padding: "30px",
            display: "flex",
            gap: "55px",
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/contact">Contact</Link>
          <Link href="/todo">Todo</Link>
          <Link href="/auth/signup">SignUp</Link>
          <Link href="/auth/signin">SignIn</Link>
        </div>

        {children}

        <div style={{ backgroundColor: "beige" }}>I am footer</div>
      </body>
    </html>
  );
}
